# SITE CONFIGURATION
title: Fadil Isamotu  # your site title
author: Fadil Isamotu # You :P
description: > # Meta description of Homepage
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/home" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github: https://github.com/Fadil-1 ## Change your github url
linkedin: https://www.linkedin.com/in/fadil-isamotu-b2b0241a1/  ## Change your linkedin url

favicon: 376843.png
# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Projects', link: '/projects'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Customize on line 29 under the config.yml file

hero_img: 1688123497021.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/1688123497021.jpg


# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
